name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install xrdp
      run: sudo apt-get install -y xrdp

    - name: Start xrdp service
      run: sudo service xrdp start

    - name: Display IP address
      run: echo "IP address: ${{ steps.set-up-ubuntu.outputs.ip-address }}"
      id: set-up-ubuntu

